language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - npm test
after_script: npm run test:coverage
after_success: cat ./test/unit/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js